language: python

services:
  - docker

install:
  - sudo pip install docker-compose

script:
  - docker pull mysql:5.7.14
  - docker pull haproxy:1.7
  - docker pull tp33/django
  - mkdir -p ~/cs4501/app
  - mkdir -p ~/cs4501/db
  - docker run -it --name web -v ~/cs4501/app:/app tp33/django bash -c "^C"
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - docker ps -a
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash -c "mysql -uroot -p'$3cureUS' -h db; create user 'www'@'%' identified by '$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%'; grant all on test_cs4501.* to 'www'@'%'; ^D; ^C;"
#  - docker build haproxy:1.7
  - docker-compose up -d
  - docker ps -a
  - sleep 100
  - docker exec pastryexchange_models_1 bash -c "python manage.py test"
  - docker ps -a
#  - pip install selenium
#  - WEB_APP_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' haproxy)
#  - SELENIUM_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' selenium)
#  - python unitTestSel.py ${SELENIUM_IP} ${WEB_APP_IP}