models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./Microservices:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; python /app/manage.py loaddata /app/db.json; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/bakery/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - es:es
      - kafka:kafka
   ports:
      - "8002:8000"
   volumes:
      - ./expservice:/app
   command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/expservice/wsgi.py"

web1:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./BakeryWebsite:/app
   command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/BakeryWebsite/wsgi.py"

web2:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8004:8000"
   volumes:
      - ./BakeryWebsite:/app
   command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/BakeryWebsite/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   ports:
      - "8003:8000"
   volumes:
      - ./batch:/batch
   command: python /batch/searchindexer.py &

haproxy:
  image: haproxy:1.7
  container_name: haproxy
  links:
    - web1
    - web2
  volumes:
    - .:/app
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  ports:
    - "8005:8000"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web1:web
  ports:
    - "8006:8000"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web1:web
  volumes:
    - .:/app
  command: bash -c "pip install selenium==3.11.0 && sleep 5 && python selenium_tests.py"

batch-spark:
   image: tp33/django
   container_name: batch-spark
   volumes:
    - ./data:/batch
   links:
      - kafka:kafka
   ports:
      - "8007:8000"   
   command: bash -c "python /batch/batch-spark.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  external_links:
    - mysql:db
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data
