mysql-cmdline:
    image: mysql:5.7.17
    container_name: mysql-cmdline
    external_links:
      - mysql:db
    command: bash -c "mysql -uroot -p'$$3cureUS' -h db; create user 'www'@'%' identified by '$$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%'; grant all on test_cs4501.* to 'www'@'%'; ^D; ^C"


models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./Microservices:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; python /app/manage.py loaddata /app/db.json; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/bakery/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - es:es
      - kafka:kafka
   ports:
      - "8002:8000"
   volumes:
      - ./expservice:/app
   command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/expservice/wsgi.py"

web1:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./BakeryWebsite:/app
   command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/BakeryWebsite/wsgi.py"

web2:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8004:8000"
   volumes:
      - ./BakeryWebsite:/app
   command: bash -c "pip install requests; /app/manage.py makemigrations api; python /app/manage.py makemigrations; python /app/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/BakeryWebsite/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   ports:
      - "8003:8000"
   volumes:
      - ./batch:/batch
   command: python /batch/searchindexer.py &

haproxy:
  image: haproxy:1.7
  container_name: haproxy
  links:
    - web1
    - web2
  volumes:
    - .:/app
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  ports:
    - "8005:8000"
